[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/aesthetic_car/*"
  [headers.values]
    Content-Type = "model/gltf+json"

[[headers]]
  for = "/planet/*"
  [headers.values]
    Content-Type = "model/gltf+json"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
